version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
    - 5.11.9
  - dependency-name: "@aws-amplify/pubsub"
    versions:
    - 3.2.16
    - 3.2.17
    - 3.2.18
    - 3.2.19
    - 3.2.20
    - 3.2.21
    - 3.2.22
    - 3.2.23
    - 3.2.24
    - 3.2.25
    - 3.2.26
    - 3.2.27
  - dependency-name: "@aws-amplify/api"
    versions:
    - 3.2.18
    - 3.2.19
    - 3.2.20
    - 3.2.21
    - 3.2.22
    - 3.2.23
    - 3.2.24
    - 3.2.25
    - 3.2.26
    - 3.2.27
    - 3.2.28
    - 3.2.29
  - dependency-name: react-bootstrap
    versions:
    - 1.4.3
    - 1.5.0
    - 1.5.1
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.3
    - 11.2.4
    - 11.2.5
  - dependency-name: react
    versions:
    - 16.14.0
  - dependency-name: jquery
    versions:
    - 3.5.1
